import {
  loadCorporationActivityMapAssets,
  loadCorporationActivityMapAssetsCapitals,
  loadCorporationActivityMapAssetsMembers,
  loadCorporationActivityMapAssetsMembersCapitals,
  loadCorporationActivityMapAssetsMembersShips,
  loadCorporationActivityMapAssetsShips,
  loadCorporationActivityMapClonesHome,
  loadCorporationActivityMapClonesJump,
  loadCorporationActivityMapContracts,
  loadCorporationActivityMapContractsLogistics,
  loadCorporationActivityMapContractsSales,
  loadCorporationActivityMapIndustry,
  loadCorporationActivityMapLocation,
  loadCorporationActivityMapMercenaryDens,
  loadCorporationActivityMapMercenaryTacticalOperations,
  loadCorporationActivityMapMining,
  loadCorporationActivityMapOrders,
  loadCorporationActivityMapOrdersMembers,
  loadCorporationActivityMapPi,
  loadCorporationActivityMapPocos,
  loadCorporationActivityMapPocosRevenue,
  loadCorporationActivityMapRatting,
  loadCorporationActivityMapStarbases,
  loadCorporationActivityMapStructures,
} from "../../../api/corporation";
import type { ActivityMapDataSource } from "../../ActivityMap/types";

// Same shape as the character-side registry (Components/Character/
// ActivityMap/dataSources.ts) - just pointed at the corp-scoped endpoints,
// which aggregate across every character/asset visible for the whole
// corporation rather than just the requesting user's own alts.
export const CORPORATION_ACTIVITY_MAP_DATA_SOURCES: ActivityMapDataSource[] = [
  {
    value: "assets",
    label: "Assets (Everything)",
    load: loadCorporationActivityMapAssets,
    countLabel: "Assets",
    quantityLabel: "Quantity",
  },
  {
    value: "assets_ships",
    label: "Assets (Ships)",
    load: loadCorporationActivityMapAssetsShips,
    countLabel: "Ships",
    quantityLabel: "Quantity",
  },
  {
    value: "assets_capitals",
    label: "Assets (Capital Ships)",
    load: loadCorporationActivityMapAssetsCapitals,
    countLabel: "Capital Ships",
    quantityLabel: "Quantity",
  },
  {
    value: "assets_members",
    label: "Member Assets (Everything)",
    load: loadCorporationActivityMapAssetsMembers,
    countLabel: "Assets",
    quantityLabel: "Quantity",
  },
  {
    value: "assets_members_ships",
    label: "Member Assets (Ships)",
    load: loadCorporationActivityMapAssetsMembersShips,
    countLabel: "Ships",
    quantityLabel: "Quantity",
  },
  {
    value: "assets_members_capitals",
    label: "Member Assets (Capital Ships)",
    load: loadCorporationActivityMapAssetsMembersCapitals,
    countLabel: "Capital Ships",
    quantityLabel: "Quantity",
  },
  {
    value: "structures",
    label: "Structures",
    load: loadCorporationActivityMapStructures,
    countLabel: "Structures",
  },
  {
    value: "starbases",
    label: "Starbases",
    load: loadCorporationActivityMapStarbases,
    countLabel: "Starbases",
  },
  {
    value: "pocos",
    label: "Customs Offices",
    load: loadCorporationActivityMapPocos,
    countLabel: "Customs Offices",
  },
  {
    value: "pocos_revenue",
    label: "Customs Office Revenue",
    load: loadCorporationActivityMapPocosRevenue,
    valueLabel: "ISK Earned",
    countLabel: "Tax Entries",
  },
  {
    value: "contracts",
    label: "Contracts (Everything)",
    load: loadCorporationActivityMapContracts,
    countLabel: "Contract Endpoints",
  },
  {
    value: "contracts_sales",
    label: "Contracts (Sales)",
    load: loadCorporationActivityMapContractsSales,
    countLabel: "Contract Endpoints",
  },
  {
    value: "contracts_logistics",
    label: "Contracts (Logistics)",
    load: loadCorporationActivityMapContractsLogistics,
    countLabel: "Contract Endpoints",
  },
  {
    value: "orders",
    label: "Market Orders",
    load: loadCorporationActivityMapOrders,
    countLabel: "Active Orders",
  },
  {
    value: "orders_members",
    label: "Member Market Orders",
    load: loadCorporationActivityMapOrdersMembers,
    countLabel: "Active Orders",
  },
  {
    value: "industry",
    label: "Industry",
    load: loadCorporationActivityMapIndustry,
    countLabel: "Industry Jobs",
  },
  {
    value: "location",
    label: "Current Location",
    load: loadCorporationActivityMapLocation,
    countLabel: "Members",
  },
  {
    value: "clones_home",
    label: "Home Clones",
    load: loadCorporationActivityMapClonesHome,
    countLabel: "Home Clones",
  },
  {
    value: "clones_jump",
    label: "Jump Clones",
    load: loadCorporationActivityMapClonesJump,
    countLabel: "Jump Clones",
  },
  {
    value: "mercenary_dens",
    label: "Member Mercenary Dens",
    load: loadCorporationActivityMapMercenaryDens,
    countLabel: "Mercenary Dens",
  },
  {
    value: "mercenary_tactical_operations",
    label: "Member Mercenary Tactical Operations",
    load: loadCorporationActivityMapMercenaryTacticalOperations,
    countLabel: "Tactical Operations",
  },
  {
    value: "pi",
    label: "Member Planetary Interaction",
    load: loadCorporationActivityMapPi,
    valueLabel: "ISK Spent",
    countLabel: "PI Entries",
  },
  {
    value: "mining",
    label: "Mining",
    load: loadCorporationActivityMapMining,
    valueLabel: "Volume (m³)",
    countLabel: "Mining Entries",
    quantityLabel: "Units Mined",
  },
  {
    value: "ratting",
    label: "Ratting",
    load: loadCorporationActivityMapRatting,
    valueLabel: "ISK Earned",
    countLabel: "Bounty Payouts",
  },
];
