# eve_sde ItemCategory id for the "Ship" category.
SHIP_CATEGORY_ID = 6

# Group ids for hull classes considered "capital ships" - the union of the
# lists already used by the asset-groups endpoints (api/character/assets.py
# and api/corporation/assets.py) to bucket "Capital Ships": Titan, Carrier,
# Supercarrier, Force Auxiliary, Dreadnought, Jump Freighter, Freighter,
# Capital Industrial Ship, Lancer Dreadnought.
CAPITAL_SHIP_GROUP_IDS = [30, 547, 659, 1538, 485, 902, 513, 883, 77283]

# The full `location_flag` enum from the ESI character/corporation assets
# endpoints (GetCharactersCharacterIdAssets / GetCorporationsCorporationIdAssets).
# Used to power the Smart Filter admin's location-flag picker.
LOCATION_FLAG_CHOICES = [
    "AssetSafety",
    "AutoFit",
    "BoosterBay",
    "CapsuleerDeliveries",
    "Cargo",
    "CorporationGoalDeliveries",
    "CorpseBay",
    "Deliveries",
    "DroneBay",
    "ExpeditionHold",
    "FighterBay",
    "FighterTube0",
    "FighterTube1",
    "FighterTube2",
    "FighterTube3",
    "FighterTube4",
    "FleetHangar",
    "FrigateEscapeBay",
    "Hangar",
    "HangarAll",
    "HiSlot0",
    "HiSlot1",
    "HiSlot2",
    "HiSlot3",
    "HiSlot4",
    "HiSlot5",
    "HiSlot6",
    "HiSlot7",
    "HiddenModifiers",
    "Implant",
    "InfrastructureHangar",
    "LoSlot0",
    "LoSlot1",
    "LoSlot2",
    "LoSlot3",
    "LoSlot4",
    "LoSlot5",
    "LoSlot6",
    "LoSlot7",
    "Locked",
    "MedSlot0",
    "MedSlot1",
    "MedSlot2",
    "MedSlot3",
    "MedSlot4",
    "MedSlot5",
    "MedSlot6",
    "MedSlot7",
    "MobileDepotHold",
    "MoonMaterialBay",
    "QuafeBay",
    "RigSlot0",
    "RigSlot1",
    "RigSlot2",
    "RigSlot3",
    "RigSlot4",
    "RigSlot5",
    "RigSlot6",
    "RigSlot7",
    "ShipHangar",
    "Skill",
    "SpecializedAmmoHold",
    "SpecializedAsteroidHold",
    "SpecializedCommandCenterHold",
    "SpecializedFuelBay",
    "SpecializedGasHold",
    "SpecializedIceHold",
    "SpecializedIndustrialShipHold",
    "SpecializedLargeShipHold",
    "SpecializedMaterialBay",
    "SpecializedMediumShipHold",
    "SpecializedMineralHold",
    "SpecializedOreHold",
    "SpecializedPlanetaryCommoditiesHold",
    "SpecializedSalvageHold",
    "SpecializedShipHold",
    "SpecializedSmallShipHold",
    "StructureDeedBay",
    "SubSystemBay",
    "SubSystemSlot0",
    "SubSystemSlot1",
    "SubSystemSlot2",
    "SubSystemSlot3",
    "SubSystemSlot4",
    "SubSystemSlot5",
    "SubSystemSlot6",
    "SubSystemSlot7",
    "Unlocked",
    "Wardrobe",
]
