# Generated by Django 2.2.9 on 2020-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0002_auto_20200507_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapregion',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
