# Generated by Django 5.2.12 on 2026-05-28 10:09

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0004_remove_old_timestamp_fields"),
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SovereigntyHub",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hub_id", models.BigIntegerField()),
                ("solar_system_id", models.IntegerField()),
                ("fuel_access_list_id", models.IntegerField(default=None, null=True)),
                ("power_allocated", models.IntegerField(default=None, null=True)),
                ("power_available", models.IntegerField(default=None, null=True)),
                ("workforce_allocated", models.IntegerField(default=None, null=True)),
                ("workforce_available", models.IntegerField(default=None, null=True)),
                ("vuln_window_start", models.DateTimeField(default=None, null=True)),
                ("vuln_window_end", models.DateTimeField(default=None, null=True)),
                ("reagent_last_updated", models.DateTimeField(
                    default=None, null=True)),
                ("workforce_transport", models.JSONField(default=None, null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ct_sovereignty_hub",
                        to="corptools.corporationaudit",
                    ),
                ),
                (
                    "solar_system_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "unique_together": {("corporation", "hub_id")},
            },
        ),
        migrations.CreateModel(
            name="SovereigntyHubReagent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("burning_per_hour", models.IntegerField()),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reagents",
                        to="corptools.sovereigntyhub",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SovereigntyHubUpgrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power_state", models.CharField(max_length=50)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="corptools.sovereigntyhub",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
        ),
    ]
