# Generated by Django 5.2.12 on 2026-06-21 04:56

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0005_sovereigntyhub_sovereigntyhubreagent_and_more"),
        ("eve_sde", "0019_alter_dogmaattribute_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="characterminingledger",
            index=models.Index(
                fields=["character_id", "date"], name="corptools_c_charact_83647a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corpasset",
            index=models.Index(
                fields=["corporation_id", "location_id"],
                name="corptools_c_corpora_cac556_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["character_id", "timestamp"],
                name="corptools_n_charact_fa4e90_idx",
            ),
        ),
    ]
