# Generated by Django 5.2.12 on 2026-06-29 12:57

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0006_add_missing_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="corptoolsconfiguration",
            name="notification_retention_days",
            field=models.IntegerField(
                default=90,
                help_text="Days to retain purgeable notification types (NPC, war, structure, sovereignty). Corp membership, player bounties, kill rights, and similar player interaction notifications are never purged.",
            ),
        ),
        migrations.AddField(
            model_name="corptoolsconfiguration",
            name="wallet_journal_retention_days",
            field=models.IntegerField(
                default=365,
                help_text="Days to retain NPC-only wallet journal entries (e.g. insurance, manufacturing fees). Player interaction entries are never purged.",
            ),
        ),
    ]
