# Generated by Django 2.2.9 on 2020-05-11 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0007_auto_20200510_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='corptools.EveItemType'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('character', 'skill_id')},
        ),
    ]
