# Generated by Django 5.2.12 on 2026-07-22 00:49

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0008_bpc_me_te_runs"),
        ("eve_sde", "0021_archetype_freelancejobschema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corptoolsconfiguration",
            name="disable_update_mercenary_dens",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Temporarily disable the ESI pulls for Character Mercenary Den Data",
            ),
        ),
        migrations.CreateModel(
            name="CharacterMercenaryDen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("den_id", models.BigIntegerField()),
                ("planet_id", models.IntegerField()),
                ("type_id", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unspecified", "unspecified"),
                            ("running", "running"),
                            ("paused", "paused"),
                            ("disabled", "disabled"),
                        ],
                        max_length=11,
                    ),
                ),
                ("development_amount", models.IntegerField(default=0)),
                (
                    "development_level",
                    models.CharField(
                        choices=[
                            ("unspecified", "unspecified"),
                            ("level0", "level0"),
                            ("level1", "level1"),
                            ("level2", "level2"),
                            ("level3", "level3"),
                            ("level4", "level4"),
                        ],
                        max_length=11,
                    ),
                ),
                ("anarchy_amount", models.IntegerField(default=0)),
                (
                    "anarchy_level",
                    models.CharField(
                        choices=[
                            ("unspecified", "unspecified"),
                            ("level0", "level0"),
                            ("level1", "level1"),
                            ("level2", "level2"),
                            ("level3", "level3"),
                            ("level4", "level4"),
                        ],
                        max_length=11,
                    ),
                ),
                ("infomorph_amount", models.IntegerField(default=0)),
                ("reinforcement_end", models.DateTimeField(default=None, null=True)),
                ("skyhook_id", models.BigIntegerField(default=None, null=True)),
                ("skyhook_planet_id", models.IntegerField(default=None, null=True)),
                (
                    "skyhook_corporation_id",
                    models.IntegerField(default=None, null=True),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ct_mercenary_den",
                        to="corptools.characteraudit",
                    ),
                ),
                (
                    "planet_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.planet",
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "den_id")},
            },
        ),
    ]
