# Generated by Django 5.2.12 on 2026-07-22 04:01

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "corptools",
            "0009_corptoolsconfiguration_disable_update_mercenary_dens_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateSectionFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                ("sections", models.JSONField(default=list)),
                (
                    "reversed_logic",
                    models.BooleanField(
                        default=False,
                        help_text="If set all members WITHOUT the selected sections loaded will pass the test.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: Character Update Section(s) Loaded",
                "verbose_name_plural": "Smart Filter: Character Update Section(s) Loaded",
            },
        ),
    ]
