# Generated by Django 5.2.12 on 2026-07-22 06:39

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0010_updatesectionfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetsfilter",
            name="location_flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Limit filter to assets held under specific location flags (e.g. AutoFit for anchored/deployed structures).",
            ),
        ),
    ]
