# Generated by Django 5.2.12 on 2026-07-26 07:55

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0011_assetsfilter_location_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="corptoolsconfiguration",
            name="disable_update_mercenary_tactical_operations",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Temporarily disable the ESI pulls for Character Mercenary Tactical Operations Data",
            ),
        ),
        migrations.CreateModel(
            name="CharacterMercenaryTacticalOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_id", models.UUIDField()),
                ("mercenary_den_id", models.BigIntegerField()),
                ("dungeon_type_id", models.BigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unspecified", "unspecified"),
                            ("available", "available"),
                            ("started", "started"),
                            ("completed", "completed"),
                            ("expired", "expired"),
                            ("removed", "removed"),
                        ],
                        max_length=11,
                    ),
                ),
                ("expires", models.DateTimeField(default=None, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ct_mercenary_tactical_operation",
                        to="corptools.characteraudit",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "operation_id")},
            },
        ),
    ]
