# Generated by Django 5.2.16 on 2026-08-09 04:01

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "corptools",
            "0012_corptoolsconfiguration_disable_update_mercenary_tactical_operations_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="characterwalletjournalentry",
            index=models.Index(
                fields=["character", "date"], name="corptools_c_charact_b38677_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterwalletjournalentry",
            index=models.Index(
                fields=["character", "ref_type", "date"],
                name="corptools_c_charact_37da13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="characterwalletjournalentry",
            index=models.Index(
                fields=["ref_type", "context_id_type", "date"],
                name="corptools_c_ref_typ_1e2c90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="corporationwalletjournalentry",
            index=models.Index(
                fields=["division", "date"], name="corptools_c_divisio_74295e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporationwalletjournalentry",
            index=models.Index(
                fields=["division", "ref_type"], name="corptools_c_divisio_c142c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporationwalletjournalentry",
            index=models.Index(
                fields=["ref_type", "context_id_type", "date"],
                name="corptools_c_ref_typ_c98dba_idx",
            ),
        ),
    ]
