# Generated by Django 5.2.12 on 2026-08-09 13:07

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "corptools",
            "0013_characterwalletjournalentry_corptools_c_charact_b38677_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PVEIskFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                (
                    "stat",
                    models.CharField(
                        choices=[
                            ("ratting", "Ratting"),
                            ("missions", "Missions"),
                            ("incursion", "Incursion"),
                            ("pochven", "Pochven"),
                        ],
                        default="ratting",
                        help_text="Which glances-page PvE stat to check.",
                        max_length=20,
                    ),
                ),
                ("isk_threshold", models.BigIntegerField(default=0)),
                ("look_back_days", models.IntegerField(default=30)),
                (
                    "reversed_logic",
                    models.BooleanField(
                        default=False,
                        help_text="If set, members who have earned LESS than the threshold will pass the test.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: PvE ISK Earned",
                "verbose_name_plural": "Smart Filter: PvE ISK Earned",
            },
        ),
    ]
