# Generated by Django 5.2.16 on 2026-08-16 04:08

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0014_pveiskfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsfilter',
            name='exclude_main_character',
            field=models.BooleanField(
                default=False, help_text="If set, each user's main character is ignored - only alts are checked."),
        ),
        migrations.AddField(
            model_name='skillfilter',
            name='exclude_main_character',
            field=models.BooleanField(
                default=False, help_text="If set, each user's main character is ignored - only alts are checked."),
        ),
    ]
