# Generated by Django 5.2.12 on 2026-08-19 10:00

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0015_assetsfilter_exclude_main_character_and_more"),
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeincorpfilter",
            name="corp",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="If set, checks time in this specific corp's most recent stint instead of the main's current corp. Leave blank to check the main's current corp as before.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eveonline.evecorporationinfo",
            ),
        ),
    ]
