# Generated by Django 5.2.12 on 2026-08-19 11:40

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0016_timeincorpfilter_corp"),
        ("eve_sde", "0036_remove_star_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiningFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                ("look_back_days", models.IntegerField(default=30)),
                (
                    "min_volume",
                    models.FloatField(
                        default=0,
                        help_text="Minimum total m3 mined (quantity x each type's unpackaged volume, across matching ore/ice/gas types) in the look-back window.",
                    ),
                ),
                ("include_high_sec", models.BooleanField(default=True)),
                ("include_low_sec", models.BooleanField(default=True)),
                ("include_null_sec", models.BooleanField(default=True)),
                ("include_w_space", models.BooleanField(default=True)),
                (
                    "reversed_logic",
                    models.BooleanField(
                        default=False,
                        help_text="If set, members who mined LESS than the threshold will pass the test.",
                    ),
                ),
                (
                    "constellations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit filter to specific constellations",
                        to="eve_sde.constellation",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit to specific ore/ice/gas groups. Leave blank for all groups.",
                        to="eve_sde.itemgroup",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit filter to specific regions",
                        to="eve_sde.region",
                    ),
                ),
                (
                    "systems",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit filter to specific systems",
                        to="eve_sde.solarsystem",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit to specific ore/ice/gas types. Leave blank for all types.",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: Mining Yield",
                "verbose_name_plural": "Smart Filter: Mining Yield",
            },
        ),
    ]
