# Generated by Django 3.1.1 on 2021-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0043_auto_20210125_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraudit',
            name='cache_expire_orders',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='characteraudit',
            name='last_update_orders',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
