# Generated by Django 3.2.5 on 2021-08-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0054_auto_20210808_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterroles',
            name='character',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='corptools.characteraudit'),
        ),
    ]
