# Generated by Django 3.2.8 on 2022-01-09 01:42

from django.db import migrations


def migrate_notifications(apps, schema_editor):
    Notification = apps.get_model('corptools', 'Notification')
    NotificationText = apps.get_model('corptools', 'NotificationText')
    print("Starting Migration: if this hangs for more than 5 min please cancel and restart.")

    existing_notes = NotificationText.objects.all().values('notification_id')
    note_ids = Notification.objects.all().values(
        'notification_id').exclude(
            notification_id__in=existing_notes).distinct()
    note_cnt = note_ids.count()
    start = 0
    step = 100000
    if note_cnt > 0:
        while start <= note_cnt:
            n = Notification.objects.all().values('notification_id').exclude(
                notification_id__in=existing_notes).distinct().order_by(
                'notification_id').values('notification_id', 'notification_text')[start:start+step]
            obs = []
            for i in n:
                obs.append(NotificationText(notification_id=i['notification_id'],
                                            notification_text=i['notification_text']))
            c = NotificationText.objects.bulk_create(
                obs, batch_size=20000, ignore_conflicts=True)
            start += step
            print(f"Migrated {start}({len(c)}) of {note_cnt}")

    newids = NotificationText.objects.all().values('notification_id')
    cnt = Notification.objects.all().exclude(notification_id__in=newids).count()

    if cnt > 0:
        print(
            f"Notifications have not been migrated fully, {cnt} missing notifications, please run `manage.py migrate --fake corptools 0061_notificationtext`  then retry migrations. If Problem persists please contact the developers")


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0061_notificationtext'),
    ]

    operations = [
        migrations.RunPython(migrate_notifications)
    ]


575322473
