# Generated by Django 3.2.8 on 2022-01-09 01:42

from django.db import migrations


def migrate_notifications(apps, schema_editor):
    Notification = apps.get_model('corptools', 'Notification')
    NotificationText = apps.get_model('corptools', 'NotificationText')
    print("Starting Migration:")
    note_ids = Notification.objects.all().values(
        'notification_id').distinct().values('id')
    note_cnt = note_ids.count()
    start = 0
    step = 1000
    while start <= note_cnt:
        nids = list(Notification.objects.all().values('notification_id').distinct(
        ).order_by('id').values_list('id', flat=True)[start:start+step])
        n = Notification.objects.filter(id__in=nids).values('notification_id').distinct(
        ).values('notification_id', 'notification_text', 'notification_type')
        n.count()
        obs = []
        for i in n:
            obs.append(NotificationText(notification_id=i['notification_id'],
                                        notification_text=i['notification_text']))
        NotificationText.objects.bulk_create(obs, ignore_conflicts=True)
        start += step
        print(f"Migrated {start} of {note_cnt}")


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0061_notificationtext'),
    ]

    operations = [
        migrations.RunPython(migrate_notifications)
    ]
