# Generated by Django 3.2.8 on 2022-01-09 10:19

from corptools.models import NotificationText
from django.db import migrations
from django.db.models import F


def migrate_notifications(apps, schema_editor):
    Notification = apps.get_model('corptools', 'Notification')
    Notification.objects.all().update(note_text=F("notification_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0064_notification_note_text'),
    ]

    operations = [
        migrations.RunPython(migrate_notifications)
    ]
