# Generated by Django 4.0.8 on 2023-02-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('corptools', '0078_characterwalletjournalentry_corptools_c_date_aebcea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraudit',
            name='last_update_loyaltypoints',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='LP')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='corptools.characteraudit', verbose_name='Character')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='eveonline.evecorporationinfo', verbose_name='NPC Corporation')),
            ],
            options={
                'verbose_name': 'Loyalty Point',
                'unique_together': {('character', 'corporation')},
            },
        ),
    ]
