# Generated by Django 4.0.8 on 2023-02-24 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0079_characteraudit_last_update_loyaltypoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='corporation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='corptools.evename', verbose_name='NPC Corporation'),
        ),
    ]
