# Generated by Django 4.0.8 on 2023-01-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0082_contract_characteraudit_last_update_contracts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='acceptor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contractacceptor', to='corptools.evename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='assignee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contractassignee', to='corptools.evename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='issuer_corporation_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contractissuercorporation', to='corptools.evename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='issuer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contractissuer', to='corptools.evename'),
            preserve_default=False,
        ),
    ]
