# Generated by Django 4.0.8 on 2023-01-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0083_contract_acceptor_name_contract_assignee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_location_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contractto', to='corptools.evelocation'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_location_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contractfrom', to='corptools.evelocation'),
        ),
    ]
