# Generated by Django 4.2.5 on 2023-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0095_lastloginfilter_no_data_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraudit',
            name='last_known_logoff',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
