# Generated by Django 4.2.16 on 2025-04-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0120_corptoolsconfiguration_aggregate_lookback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharAssetCoordiante',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                 related_name='coordinate', serialize=False, to='corptools.characterasset')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
    ]
